---
title: "Dades cabines"
author: "Eudald"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(RSocrata)
```

```{r}
url <- "https://analisi.transparenciacatalunya.cat/resource/tasf-thgu.json"
q <- "?$where= data >= '2014-01-01' and data <= '2020-03-13'"
l <- paste0(url, q)
data <- read.socrata(l, stringsAsFactors = F)
```

```{r}
contaminants <- c("O3", "NO", "NO2", "NOX", "SO2", "PM10")
tgn <- c(
  "Tarragona (Bonavista)",
  "Tarragona (Parc de la Ciutat)",
  "Tarragona (Sant Salvador)",
  "Tarragona (Universitat Laboral)"
)
bcn <- c(
  "Barcelona (Ciutadella)",
  "Barcelona (Eixample)",
  "Barcelona (Gràcia - Sant Gervasi)",
  "Barcelona (Observatori Fabra)",
  "Barcelona (Palau Reial)",
  "Barcelona (Parc Vall Hebron)",
  "Barcelona (Poblenou)",
  "Barcelona (Sants)"
)
hospitals <- c(
  "01" = tgn,
  "02" = "Alcover",
  "03" = "Reus",
  "04" = tgn,
  "05" = "Vilafranca del Penedès",
  "06" = "Amposta",
  "07" = "Mataró",
  "08" = bcn,
  "09" = "Terrassa",
  "10" = bcn,
  "11" = "Terrassa",
  "12" = "Girona (Escola de Música)",
  "13" = "Manresa",
  "14" = "Sant Feliu de Ll. (CEIP Marti i Pol)",
  "16" = "L'Hospitalet de Llobregat",
  "17" = "Santa Coloma de Gramenet",
  "19" = bcn,
  "20" = bcn,
  "21" = "Lleida"
)
hospitals2 <- c(
  "01" = "Tarragona",
  "02" = "Alcover",
  "03" = "Reus",
  "04" = "Tarragona",
  "05" = "Vilafranca del Penedès",
  "06" = "Amposta",
  "07" = "Mataró",
  "08" = "Barcelona",
  "09" = "Terrassa",
  "10" = "Barcelona",
  "11" = "Terrassa",
  "12" = "Girona",
  "13" = "Manresa",
  "14" = "Sant Feliu de Llobregat",
  "16" = "L'Hospitalet de Llobregat",
  "17" = "Santa Coloma de Gramenet",
  "19" = "Barcelona",
  "20" = "Barcelona",
  "21" = "Lleida"
)
```

```{r}
estacions <- c(
  "Alcover" = "Alcover", 
  "Amposta" = "Amposta",
  "Barcelona (Ciutadella)" = "Barcelona",
  "Barcelona (Eixample)" = "Barcelona",
  "Barcelona (Gràcia - Sant Gervasi)" = "Barcelona",
  "Barcelona (Observatori Fabra)" = "Barcelona",
  "Barcelona (Palau Reial)" = "Barcelona",
  "Barcelona (Parc Vall Hebron)" = "Barcelona",
  "Barcelona (Poblenou)" = "Barcelona",
  "Barcelona (Sants)" = "Barcelona",
  "Tarragona (Bonavista)" = "Tarragona",
  "Tarragona (Parc de la Ciutat)" = "Tarragona",
  "Tarragona (Sant Salvador)" = "Tarragona",
  "Tarragona (Universitat Laboral)" = "Tarragona",
  "Reus" = "Reus",
  "Vilafranca del Penedès" = "Vilafranca del Penedès",
  "Mataró" = "Mataró",
  "Terrassa" = "Terrassa",
  "Girona (Escola de Música)" = "Girona",
  "Manresa" = "Manresa",
  "Sant Feliu de Ll. (CEIP Marti i Pol)" = "Sant Feliu de Llobregat",
  "L'Hospitalet de Llobregat" = "L'Hospitalet de Llobregat",
  "Santa Coloma de Gramenet" = "Santa Coloma de Gramenet",
  "Lleida" = "Lleida"
  )

openxlsx::write.xlsx(as.data.frame(estacions) %>% tibble::rownames_to_column(), "estacions.xlsx")
```

```{r}
na_mean <- function(x) mean(x, na.rm = T)
aa <- data %>%
    filter(
    nom_estacio %in% unname(hospitals),
    contaminant %in% contaminants,
  ) %>%
  mutate(
    plobacio = estacions[nom_estacio]
  ) %>%
  pivot_longer(starts_with("h")) %>%
  mutate(value = as.numeric(value)) %>%
  group_by(plobacio, contaminant) %>%
  summarise(across(value, na_mean)) %>%
  pivot_wider(names_from = c(contaminant), values_from=value)
```

```{r}
bb <- missForest::missForest(as.data.frame(aa)[, -1])
cc <- bb$ximp %>%
  mutate(poblacio = aa$plobacio)
```

```{r}
openxlsx::write.xlsx(cc, "contaminació_final.xlsx")
```

