---
title: "mapa"
author: "Eudald"
date: "29/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(leaflet)
library(dplyr)
```



Estacions

```{r}
tgn <- c(
  "Tarragona (Bonavista)",
  "Tarragona (Parc de la Ciutat)",
  "Tarragona (Sant Salvador)",
  "Tarragona (Universitat Laboral)"
)
bcn <- c(
  "Barcelona (Ciutadella)",
  "Barcelona (Eixample)",
  "Barcelona (Gràcia - Sant Gervasi)",
  "Barcelona (Observatori Fabra)",
  "Barcelona (Palau Reial)",
  "Barcelona (Parc Vall Hebron)",
  "Barcelona (Poblenou)",
  "Barcelona (Sants)"
)
hospitals <- c(
  "01" = tgn,
  "02" = "Alcover",
  "03" = "Reus",
  "04" = tgn,
  "05" = "Vilafranca del Penedès",
  "06" = "Amposta",
  "07" = "Mataró",
  "08" = bcn,
  "09" = "Terrassa",
  "10" = bcn,
  "11" = "Terrassa",
  "12" = "Girona (Escola de Música)",
  "13" = "Manresa",
  "14" = "Sant Feliu de Ll. (CEIP Marti i Pol)",
  "19" = bcn,
  "20" = bcn
)
hosps <- unique(unname(hospitals))
```

```{r}
url <- "https://analisi.transparenciacatalunya.cat/resource/tasf-thgu.json"
q <- "?$where= data >= '2021-03-28'"
l <- paste0(url, q)
data <- RSocrata::read.socrata(l, stringsAsFactors = F) %>%
  filter(nom_estacio %in% hosps) %>%
  dplyr::select(nom_estacio, latitud, longitud) %>%
  distinct()
```

```{r}
hosp_icon <- awesomeIcons(
  icon = "hospital", 
  iconColor = "yellow", 
  markerColor = "blue",
  library = "fa"
)
```


```{r}
leaflet() %>%
  addProviderTiles(provider = providers$OpenStreetMap.Mapnik) %>%
  addAwesomeMarkers(lng = hos$longitud, lat = hos$latitud, icon = hosp_icon)
```

```{r}
library(ggmap)
cat <- c(left = 0, bottom = 40, right = 4, top = 43)
get_stamenmap(cat, zoom = 7, maptype = "terrain-labels") %>% 
  ggmap() 
get_googlemap("waco texas", zoom = 12) %>% ggmap()
```


```{r}
library(sf)
map <- st_read("LIMADM_COMARCA/LIMADM_COMARCA.shp")
mapa <- rmapshaper::ms_simplify(st_transform(map, "+proj=longlat +datum=WGS84"))
mapa %>%
  leaflet() %>%
     addProviderTiles(providers$OpenStreetMap.Mapnik) %>%
        addPolygons(
          weight = 2,
          smoothFactor = 0.2,
          fillOpacity = 0.9,
          color = "black",
          fillColor = "white"
        ) %>%
  addAwesomeMarkers(lng = hos$longitud, lat = hos$latitud, icon = hosp_icon, label = hos$nom)
```

```{r}
library(tmap)
```
```{r}
icona <- tmap_icons("icones/edificios-hospitalarios.png")
```

Hospitals

```{r}
hos <- readxl::read_excel("dades/hospitals (9).xlsx") %>%
  mutate(across(starts_with("l"), as.numeric))
```


```{r}
hosm <- hos %>% 
  st_as_sf(coords = c("longitud", "latitud"))

est <- st_as_sf(data, coords = c("longitud", "latitud"))

marge <- 0.75
bb <-
  st_bbox(c(
    ymin = min(st_coordinates(mapa)[, 2]) - marge,
    ymax = max(st_coordinates(mapa)[, 2]) + marge,
    xmin = min(st_coordinates(mapa)[, 1]) - marge / 2,
    xmax = max(st_coordinates(mapa)[, 1] + marge * 1.5)
  ),  crs = st_crs(4326))

cat <- tm_shape(mapa, bbox = bb) + 
  tm_fill() +
  tm_borders() +
  tm_shape(hosm) +
  tm_symbols( size = 0.5, col = "red", border.col = "black") + 
  tm_shape(est) + 
  tm_symbols( size = 0.5, col = "blue", border.col = "black") 
```

```{r}

bb <- st_bbox(c(ymin = 41.08, ymax = 41.2, xmax = 1.1, xmin = 1.3), crs = st_crs(4326))
tgn <- tm_shape(mapa, bbox = bb) + 
  tm_fill() +
  tm_borders() +
  tm_shape(hosm) +
  tm_symbols( size = 0.5, col = "red", border.col = "black") + 
  tm_shape(est) + 
  tm_symbols( size = 0.5, col = "blue", border.col = "black") 
```

```{r}
bb <- st_bbox(c(ymin = 41.36, ymax = 41.45, xmax = 2.1, xmin = 2.22), crs = st_crs(4326))
bcn <- tm_shape(mapa, bbox = bb) + 
  tm_fill() +
  tm_borders() +
  tm_shape(hosm) +
  tm_symbols( size = 0.5, col = "red", border.col = "black") + 
  tm_shape(est) + 
  tm_symbols( size = 0.5, col = "blue", border.col = "black") 
bcn
```

```{r}
bb <- st_bbox(c(ymin = 34, ymax = 72, xmax = -25, xmin = 45), crs = st_crs(4326))
eu <- st_read("eu/ne_10m_admin_0_countries.shp")
eu <- rmapshaper::ms_simplify(st_transform(eu, "+proj=longlat +datum=WGS84"))
eur <- tm_shape(eu, bbox = bb) + 
  tm_fill() + 
  tm_borders()
```

```{r}
library(grid)
cat
print(tgn, vp = viewport(0.45, 0.2, width = 0.15, height = 0.15))
print(bcn, vp = viewport(0.6, 0.33, width = 0.2, height = 0.2))
print(eur, vp = viewport(0.661, 0.86, width = 0.4, height = 0.25))
```

